repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-ast
    - id: check-builtin-literals
    - id: check-docstring-first
    - id: check-merge-conflict
    - id: check-yaml
    - id: check-toml
      exclude: tests/packages/test-(bad-syntax|no-permission)/pyproject.toml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: double-quote-string-fixer
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
    - id: pyupgrade
    args: ["--py36-plus"]
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    - id: isort
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.20.0
    hooks:
    - id: setup-cfg-fmt
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args: [--max-line-length=100]
-   repo: https://github.com/codespell-project/codespell
    rev: "v2.1.0"
    hooks:
    - id: codespell
      args: ["-L", "sur"]
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7
    hooks:
    - id: autopep8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.902
    hooks:
    - id: mypy
      additional_dependencies: [types-all]
-   repo: https://github.com/econchick/interrogate
    rev: 1.4.0
    hooks:
      - id: interrogate
        args: ["-v", "-i"]
